
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SOOD's
 */
public class Cafe_Menu_Modify extends javax.swing.JFrame {

    /**
     * Creates new form Cafe_Menu_Modify
     */
    public Cafe_Menu_Modify() {
        initComponents();
        PanelMenu.setFocusable(false);
        TxtFdItemCategory.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgAddOrModify = new javax.swing.ButtonGroup();
        BgMenuCourse = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        RbBeverage = new javax.swing.JRadioButton();
        RbMainCourse = new javax.swing.JRadioButton();
        RbDesserts = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListMenu = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        RbAddItem = new javax.swing.JRadioButton();
        RbModifyItem = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtFdBackMainMenu = new javax.swing.JButton();
        TxtFdItemCost = new javax.swing.JTextField();
        TxtFdItemCategory = new javax.swing.JTextField();
        BtnAddChange = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        TxtFdItemName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cafe Menu Modify");

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cafe Menu Modification");

        PanelMenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu Section :"));

        BgMenuCourse.add(RbBeverage);
        RbBeverage.setText("Beverages");
        RbBeverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbBeverageActionPerformed(evt);
            }
        });

        BgMenuCourse.add(RbMainCourse);
        RbMainCourse.setText("Main Course");
        RbMainCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbMainCourseActionPerformed(evt);
            }
        });

        BgMenuCourse.add(RbDesserts);
        RbDesserts.setText("Desserts");
        RbDesserts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbDessertsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RbBeverage)
                    .addComponent(RbMainCourse)
                    .addComponent(RbDesserts))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RbBeverage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbMainCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RbDesserts))
        );

        ListMenu.setModel(new DefaultListModel());
        ListMenu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListMenu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListMenuValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListMenu);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHOOSE ONE OPTION :", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        BgAddOrModify.add(RbAddItem);
        RbAddItem.setText("Add New Item");
        RbAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbAddItemActionPerformed(evt);
            }
        });

        BgAddOrModify.add(RbModifyItem);
        RbModifyItem.setText("Modify Existing Item");
        RbModifyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbModifyItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RbAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(RbModifyItem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbAddItem)
                    .addComponent(RbModifyItem))
                .addContainerGap())
        );

        jLabel3.setText("Item Cost            :");

        jLabel4.setText("Category             :");

        TxtFdBackMainMenu.setText("BACK");
        TxtFdBackMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFdBackMainMenuActionPerformed(evt);
            }
        });

        BtnAddChange.setText("ADD/CHANGE");
        BtnAddChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddChangeActionPerformed(evt);
            }
        });

        BtnReset.setText("RESET");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        jLabel2.setText("Item Name           :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(TxtFdItemCost, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                                    .addComponent(TxtFdItemCategory)
                                                    .addComponent(TxtFdItemName)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BtnAddChange, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 17, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addComponent(TxtFdBackMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFdItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFdItemCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFdItemCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnAddChange)
                            .addComponent(BtnReset))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFdBackMainMenu)))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbBeverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbBeverageActionPerformed
        ListMenu.clearSelection();
        DefaultListModel ListMenuModel = (DefaultListModel) ListMenu.getModel();
        ListMenuModel.clear();

        String Q = "Select * from Menu where Category='Beverage'";

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aditya_sud?user="+"root"+"&password="+"MYSQL");

            Statement stmt = con.createStatement();

            ResultSet rs = stmt.executeQuery(Q);
            while(rs.next())
            {
                int itemno = rs.getInt("Item_No");
                String name = rs.getString("Item_Name");
                String cost = rs.getString("Cost");
                ListMenuModel.addElement("" + itemno + "-" + name + " : Rs." + cost);
            }

            ListMenu.setModel(ListMenuModel);
            TxtFdItemCategory.setText("Beverage");

        }

        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_RbBeverageActionPerformed

    private void RbMainCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbMainCourseActionPerformed
        // TODO add your handling code here:
        ListMenu.clearSelection();
        DefaultListModel ListMenuModel = (DefaultListModel) ListMenu.getModel();
        ListMenuModel.clear();

        String Q = "Select * from Menu where Category='Main Course'";

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aditya_sud?user="+"root"+"&password="+"MYSQL");

            Statement stmt = con.createStatement();

            ResultSet rs = stmt.executeQuery(Q);
            while(rs.next())
            {
                int itemno = rs.getInt("Item_No");
                String name = rs.getString("Item_Name");
                String cost = rs.getString("Cost");
                ListMenuModel.addElement("" + itemno + "-" + name + " : Rs." + cost);
            }

            ListMenu.setModel(ListMenuModel);
            TxtFdItemCategory.setText("Main Course");

        }

        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_RbMainCourseActionPerformed

    private void RbDessertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbDessertsActionPerformed
        // TODO add your handling code here:
        ListMenu.clearSelection();
        DefaultListModel ListMenuModel = (DefaultListModel) ListMenu.getModel();
        ListMenuModel.clear();

        String Q = "Select * from Menu where Category='Dessert'";

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aditya_sud?user="+"root"+"&password="+"MYSQL");

            Statement stmt = con.createStatement();

            ResultSet rs = stmt.executeQuery(Q);
            while(rs.next())
            {
                int itemno = rs.getInt("Item_No");
                String name = rs.getString("Item_Name");
                String cost = rs.getString("Cost");
                ListMenuModel.addElement("" + itemno + "-" + name + " : Rs." + cost);
            }

            ListMenu.setModel(ListMenuModel);
            TxtFdItemCategory.setText("Dessert");
        }

        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_RbDessertsActionPerformed

    private void ListMenuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListMenuValueChanged
        String item, name = "", cost = "";
        int i;

        item = (String) ListMenu.getSelectedValue();

        if(!ListMenu.isSelectionEmpty())
        {
            i = item.indexOf("Rs.");
            cost = item.substring(i);
            name = item.substring(0,i-3);
        }

        TxtFdItemName.setText(name);
        TxtFdItemCost.setText(cost);

    }//GEN-LAST:event_ListMenuValueChanged

    private void RbAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbAddItemActionPerformed
        ListMenu.setEnabled(false);
        BtnAddChange.setText("ADD ITEM");
        TxtFdItemCost.setText("Rs.");
        TxtFdItemName.setText("");
        RbBeverage.doClick();

    }//GEN-LAST:event_RbAddItemActionPerformed

    private void RbModifyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbModifyItemActionPerformed
        // TODO add your handling code here:
        ListMenu.setEnabled(true);
        BtnAddChange.setText("MODIFY ITEM");
        TxtFdItemCost.setText("");
        TxtFdItemName.setText("");
        RbBeverage.doClick();

    }//GEN-LAST:event_RbModifyItemActionPerformed

    private void BtnAddChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddChangeActionPerformed
        String name="", category, Q1="";
        int cost, item_no=0, opt=0;

        category = TxtFdItemCategory.getText();

        cost=Integer.parseInt((TxtFdItemCost.getText()).substring(3));

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aditya_sud?user="+"root"+"&password="+"MYSQL");

            Statement stmt = con.createStatement();

            if((BtnAddChange.getText()).equals("ADD ITEM"))
            {
                opt=1;
                String Q2 ="Select * from Menu" ;
                ResultSet rs2 = stmt.executeQuery(Q2);
                rs2.last();
                item_no = (rs2.getRow() + 1);
                name = TxtFdItemName.getText();
                Q1 = "Insert into Menu values(" + item_no + ",'" + name + "','" + category + "'," + cost + ")";

            }
            else if((BtnAddChange.getText()).equals("MODIFY ITEM"))
            {
                opt=2;
                String nameid = TxtFdItemName.getText();
                int i = nameid.indexOf("-");
                item_no = Integer.parseInt(nameid.substring(0, i));
                name = nameid.substring(i+1);
                Q1 = "Update Menu set Item_Name='" + name + "', Cost=" + cost + " WHERE Item_No=" + item_no + "";
            }

            stmt.executeUpdate(Q1);
            
            if(opt==1)
            {
             JOptionPane.showMessageDialog(this, "New item : " + name + " - Rs." + cost + " has been introduced in the " + category + " category.");   
             RbAddItem.doClick();            
            }
            else if(opt==2)
            {
                JOptionPane.showMessageDialog(this, "Item No-" + item_no +" has been updated to " + name + " : Rs." + cost);
                RbModifyItem.doClick();            
            }
            
            BtnReset.doClick();

            }


        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_BtnAddChangeActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        RbBeverage.doClick();
        RbAddItem.doClick();
    }//GEN-LAST:event_BtnResetActionPerformed

    private void TxtFdBackMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFdBackMainMenuActionPerformed
        // TODO add your handling code here:
        (new Maintenance_Menu()).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_TxtFdBackMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe_Menu_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe_Menu_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe_Menu_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe_Menu_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe_Menu_Modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BgAddOrModify;
    private javax.swing.ButtonGroup BgMenuCourse;
    private javax.swing.JButton BtnAddChange;
    private javax.swing.JButton BtnReset;
    private javax.swing.JList ListMenu;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JRadioButton RbAddItem;
    private javax.swing.JRadioButton RbBeverage;
    private javax.swing.JRadioButton RbDesserts;
    private javax.swing.JRadioButton RbMainCourse;
    private javax.swing.JRadioButton RbModifyItem;
    private javax.swing.JButton TxtFdBackMainMenu;
    private javax.swing.JTextField TxtFdItemCategory;
    private javax.swing.JTextField TxtFdItemCost;
    private javax.swing.JTextField TxtFdItemName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
