
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Guest_Details_Modify.java
 *
 * Created on Nov 25, 2014, 9:32:23 AM
 */

/**
 *
 * @author student
 */
public class Guest_Details_Modify extends javax.swing.JFrame {

    /** Creates new form Guest_Details_Modify */
    public Guest_Details_Modify() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnModify = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtArCompn = new javax.swing.JTextArea();
        TxtFdCheck_in = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtArAddress = new javax.swing.JTextArea();
        TxtFdE_id = new javax.swing.JTextField();
        TxtFdProf = new javax.swing.JTextField();
        TxtFdMobNo = new javax.swing.JTextField();
        TxtFdName = new javax.swing.JTextField();
        TxtFdG_id = new javax.swing.JTextField();
        BtnDelete = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BtnSearchName = new javax.swing.JButton();
        BtnSearchG_id = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guest Details Modify");

        BtnModify.setText("MODIFY");
        BtnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifyActionPerformed(evt);
            }
        });

        jLabel5.setText("Profession          :");

        jLabel6.setText("Email-id              :");

        jLabel7.setText("Address             :");

        jLabel2.setText("Guest_Id           :");

        jLabel3.setText("Name                 :");

        jLabel4.setText("Mob_No             :");

        jLabel9.setText("Companions       :");

        TxtArCompn.setColumns(20);
        TxtArCompn.setRows(5);
        jScrollPane2.setViewportView(TxtArCompn);

        TxtArAddress.setColumns(20);
        TxtArAddress.setRows(5);
        jScrollPane1.setViewportView(TxtArAddress);

        BtnDelete.setText("DELETE");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnBack.setText("BACK");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("GUEST DETAILS MODIFICATION");

        BtnSearchName.setText("SEARCH");
        BtnSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchNameActionPerformed(evt);
            }
        });

        BtnSearchG_id.setText("SEARCH");
        BtnSearchG_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchG_idActionPerformed(evt);
            }
        });

        BtnReset.setText("RESET");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        jLabel12.setText("( YYYY/MM/DD) : ");

        jLabel1.setText("Check-In Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnModify, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel12))
                                .addGap(0, 6, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtFdCheck_in, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtFdName)
                                        .addComponent(TxtFdG_id)
                                        .addComponent(TxtFdMobNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TxtFdProf)
                                    .addComponent(TxtFdE_id)
                                    .addComponent(jScrollPane1))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BtnSearchName)
                                    .addComponent(BtnSearchG_id)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtFdG_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnSearchG_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFdMobNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BtnSearchName)))
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFdProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFdE_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFdCheck_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnModify)
                    .addComponent(BtnDelete)
                    .addComponent(BtnReset)
                    .addComponent(BtnBack))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifyActionPerformed
        String G_id = "0", name, prof, mob_no, e_id, address, compn, room_no;
        
        G_id = TxtFdG_id.getText();
        name = TxtFdName.getText();
        prof = TxtFdProf.getText();
        mob_no = TxtFdMobNo.getText();
        e_id = TxtFdE_id.getText();
        address = TxtArAddress.getText();
        compn = TxtArCompn.getText();
        
               
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aditya_sud?user="+"root"+"&password="+"MYSQL");
            
            Statement stmt = con.createStatement();
            
            String Q1 ="Update Guest_Details set Profession='" + prof + "', Mob_No='" + mob_no + "', Email_id='" + e_id + "', Address='" + address + "', Companions='" + compn + "' WHERE G_Id='" + G_id + "'";
            stmt.executeUpdate(Q1);
            
            JOptionPane.showMessageDialog(this, "Details of Guest " + name + " (Id - " + G_id + ") have been modified.");

            BtnReset.doClick();

            }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BtnModifyActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        String G_id, name;
        
        G_id = TxtFdG_id.getText();
        name = TxtFdName.getText();       
               
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aditya_sud?user="+"root"+"&password="+"MYSQL");
            
            Statement stmt = con.createStatement();
            
            String Q1 ="Delete from Guest_Details where G_Id='" + G_id + "'";
            String Q2 ="Update Room set Status='N' where Status='" + G_id + "'";
            String Q3 ="Delete from Bill where Bill_Id='" + G_id + "'";
            stmt.executeUpdate(Q1);
            stmt.executeUpdate(Q2);
            stmt.executeUpdate(Q3);
            
            JOptionPane.showMessageDialog(this, "Details of Guest " + name + " (Id - " + G_id + ") have been removed from the Guest Details Record.");

            BtnReset.doClick();

            }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnSearchG_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchG_idActionPerformed
        String G_id , name="", prof="", mob_no="", e_id="", address="", chk_in="", compn="", room_no="";
        
        G_id = TxtFdG_id.getText();        
               
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aditya_sud?user="+"root"+"&password="+"MYSQL");
            
            Statement stmt = con.createStatement();
            
            String Q1 ="Select * from Guest_Details where G_Id='" + G_id + "'" ;
            ResultSet rs1 = stmt.executeQuery(Q1);
            if(rs1.next())
            {
                name = rs1.getString("Name");
                prof = rs1.getString("Profession");
                mob_no = rs1.getString("Mob_No");
                e_id = rs1.getString("Email_id");
                address = rs1.getString("Address");
                chk_in = rs1.getString("Check_In");
                compn = rs1.getString("Companions");
            }
            TxtFdName.setText(name);
            TxtFdProf.setText(prof);
            TxtFdMobNo.setText(mob_no);
            TxtFdE_id.setText(e_id);
            TxtArAddress.setText(address);
            TxtFdCheck_in.setText(chk_in);
            TxtArCompn.setText(compn);
            
            BtnSearchG_id.setEnabled(false);
            BtnSearchName.setEnabled(false);
            TxtFdG_id.setEditable(false);
            TxtFdName.setEditable(false);
            TxtFdMobNo.setEditable(false);
            TxtFdCheck_in.setEditable(false);
            
            }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BtnSearchG_idActionPerformed

    private void BtnSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchNameActionPerformed
        // TODO add your handling code here:
        String G_id="" , name="", prof="", mob_no="", e_id="", address="", chk_in="", compn="", room_no="";
        
        name = TxtFdName.getText();
        mob_no = TxtFdMobNo.getText();
               
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aditya_sud?user="+"root"+"&password="+"MYSQL");
            
            Statement stmt = con.createStatement();
            
            String Q1 ="Select * from Guest_Details where Name='" + name + "' AND Mob_No='" + mob_no + "'" ;
            ResultSet rs1 = stmt.executeQuery(Q1);
            if(rs1.next())
            {
                G_id = rs1.getString("G_Id");
                prof = rs1.getString("Profession");
                e_id = rs1.getString("Email_id");
                address = rs1.getString("Address");
                chk_in = rs1.getString("Check_In");
                compn = rs1.getString("Companions");
            }
            TxtFdG_id.setText(G_id);
            TxtFdProf.setText(prof);
            TxtFdE_id.setText(e_id);
            TxtArAddress.setText(address);
            TxtFdCheck_in.setText(chk_in);
            TxtArCompn.setText(compn);
            
            BtnSearchG_id.setEnabled(false);
            BtnSearchName.setEnabled(false);
            TxtFdG_id.setEditable(false);
            TxtFdName.setEditable(false);
            TxtFdMobNo.setEditable(false);
            TxtFdCheck_in.setEditable(false);
            
            }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BtnSearchNameActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        TxtFdG_id.setText("");
        TxtFdName.setText("");
        TxtFdMobNo.setText("");
        TxtFdProf.setText("");
        TxtFdE_id.setText("");
        TxtFdCheck_in.setText("");
        
        TxtArAddress.setText("");
        TxtArCompn.setText("");
        
        BtnSearchG_id.setEnabled(true);
        BtnSearchName.setEnabled(true);
        TxtFdG_id.setEditable(true);
        TxtFdName.setEditable(true);
        TxtFdMobNo.setEditable(true);
        TxtFdCheck_in.setEditable(true);

        
    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        (new Maintenance_Menu()).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_BtnBackActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guest_Details_Modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnModify;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSearchG_id;
    private javax.swing.JButton BtnSearchName;
    private javax.swing.JTextArea TxtArAddress;
    private javax.swing.JTextArea TxtArCompn;
    private javax.swing.JTextField TxtFdCheck_in;
    private javax.swing.JTextField TxtFdE_id;
    private javax.swing.JTextField TxtFdG_id;
    private javax.swing.JTextField TxtFdMobNo;
    private javax.swing.JTextField TxtFdName;
    private javax.swing.JTextField TxtFdProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
