/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Maintenance_Menu.java
 *
 * Created on Nov 25, 2014, 10:00:35 AM
 */

/**
 *
 * @author student
 */
public class Maintenance_Menu extends javax.swing.JFrame {

    /** Creates new form Maintenance_Menu */
    public Maintenance_Menu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnModGstDet = new javax.swing.JButton();
        BtnModRoomRec = new javax.swing.JButton();
        BtnModCafeMenu = new javax.swing.JButton();
        BtnModAddtCharges = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maintenance Menu");

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MAINTENANCE MENU");

        BtnModGstDet.setText("Modify Guest Details");
        BtnModGstDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModGstDetActionPerformed(evt);
            }
        });

        BtnModRoomRec.setText("Modify Rooms Record");
        BtnModRoomRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModRoomRecActionPerformed(evt);
            }
        });

        BtnModCafeMenu.setText("Modify Café Menu");
        BtnModCafeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModCafeMenuActionPerformed(evt);
            }
        });

        BtnModAddtCharges.setText("Modify Additional Charges");
        BtnModAddtCharges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModAddtChargesActionPerformed(evt);
            }
        });

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModAddtCharges, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModCafeMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModRoomRec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModGstDet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnModGstDet)
                .addGap(18, 18, 18)
                .addComponent(BtnModRoomRec)
                .addGap(18, 18, 18)
                .addComponent(BtnModCafeMenu)
                .addGap(18, 18, 18)
                .addComponent(BtnModAddtCharges)
                .addGap(32, 32, 32)
                .addComponent(BtnBack)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        (new Main_Menu()).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnModGstDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModGstDetActionPerformed
        (new Guest_Details_Modify()).setVisible(true);
         this.setVisible(false);

    }//GEN-LAST:event_BtnModGstDetActionPerformed

    private void BtnModRoomRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModRoomRecActionPerformed
        (new Room_Modify()).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_BtnModRoomRecActionPerformed

    private void BtnModCafeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModCafeMenuActionPerformed
        (new Cafe_Menu_Modify()).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_BtnModCafeMenuActionPerformed

    private void BtnModAddtChargesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModAddtChargesActionPerformed
        (new Additional_Charges_Modify()).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_BtnModAddtChargesActionPerformed

    
    
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maintenance_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnModAddtCharges;
    private javax.swing.JButton BtnModCafeMenu;
    private javax.swing.JButton BtnModGstDet;
    private javax.swing.JButton BtnModRoomRec;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
