
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main_Menu.java
 *
 * Created on Nov 21, 2014, 10:58:47 AM
 */

/**
 *
 * @author student
 */
public class Main_Menu extends javax.swing.JFrame {

    /** Creates new form Main_Menu */
    public Main_Menu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnBookRoom = new javax.swing.JButton();
        BtnOrderMeal = new javax.swing.JButton();
        BtnPrintBill = new javax.swing.JButton();
        BtnMaintFrame = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THE LONG HAUL MOTEL");

        BtnBookRoom.setText("Book Room");
        BtnBookRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBookRoomActionPerformed(evt);
            }
        });

        BtnOrderMeal.setText("Order Meal");
        BtnOrderMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrderMealActionPerformed(evt);
            }
        });

        BtnPrintBill.setText("Print Bill");
        BtnPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintBillActionPerformed(evt);
            }
        });

        BtnMaintFrame.setText("Maintenance");
        BtnMaintFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMaintFrameActionPerformed(evt);
            }
        });

        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnMaintFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPrintBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnOrderMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBookRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnBookRoom)
                .addGap(27, 27, 27)
                .addComponent(BtnOrderMeal)
                .addGap(27, 27, 27)
                .addComponent(BtnPrintBill)
                .addGap(30, 30, 30)
                .addComponent(BtnMaintFrame)
                .addGap(29, 29, 29)
                .addComponent(BtnExit)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        JOptionPane.showMessageDialog(this, "Have a Nice Day!");
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnBookRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBookRoomActionPerformed
        Rooms_Preview p = new Rooms_Preview();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnBookRoomActionPerformed

    private void BtnOrderMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrderMealActionPerformed
        (new Fat_Boy_Cafe()).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_BtnOrderMealActionPerformed

    private void BtnPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintBillActionPerformed
        (new Print_Bill()).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_BtnPrintBillActionPerformed

    private void BtnMaintFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMaintFrameActionPerformed
        (new Maintenance_Menu()).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_BtnMaintFrameActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBookRoom;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnMaintFrame;
    private javax.swing.JButton BtnOrderMeal;
    private javax.swing.JButton BtnPrintBill;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
