
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Rooms_Preview.java
 *
 * Created on Nov 24, 2014, 10:00:40 AM
 */

/**
 *
 * @author student
 */
public class Rooms_Preview extends javax.swing.JFrame {

    /** Creates new form Rooms_Preview */
    public Rooms_Preview() {
        initComponents();
        TxtArRoomDesc.setEditable(false);
        RbSlv.doClick();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgRoomType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        BtnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtArRoomDesc = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        RbSlv = new javax.swing.JRadioButton();
        RbGld = new javax.swing.JRadioButton();
        RbPlt = new javax.swing.JRadioButton();
        LblRoomPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rooms Preview");

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ROOMS PREVIEW");

        BtnBack.setText("BACK");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        BtnNext.setText("NEXT");
        BtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNextActionPerformed(evt);
            }
        });

        TxtArRoomDesc.setColumns(20);
        TxtArRoomDesc.setRows(5);
        TxtArRoomDesc.setText("SILVER CLASS ROOMS :\nThese are furbished with a 32' LCD, a Single bed, a Work-table &\nChairs, Hot-water connection to the bath, & free of cost provision\nof basic ammenities.\nComplimentary : Daily Breakfast at our cafe.\n\n\nGOLD CLASS ROOMS :\nThese are furbished with a 40' LCD, a Double bed, a Work-table &\nChairs, a Sofa, Hot-water connection to the bath, an Air-Conditioner\n& free of cost provision of basic ammenities.\nComplimentary : Daily Breakfast at our cafe, & Tea in the evening.\n\n\nPLATINUM CLASS ROOMS :\nThese are furbished with a 50' LED, a King-size bed, a Work-table &\nChairs, Free Wi-fi, two Sofas, Hot-water connection to the bath, \na private Jaccuzi, an Air-Conditioner & free of cost provision \nof basic ammenities.\nComplimentary : Daily Breakfast (served in your room), & Tea in the\nevening.");
        jScrollPane1.setViewportView(TxtArRoomDesc);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select A Room Type :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        BgRoomType.add(RbSlv);
        RbSlv.setText("SILVER CLASS");
        RbSlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbSlvActionPerformed(evt);
            }
        });

        BgRoomType.add(RbGld);
        RbGld.setText("GOLD CLASS");
        RbGld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbGldActionPerformed(evt);
            }
        });

        BgRoomType.add(RbPlt);
        RbPlt.setText("PLATINUM CLASS");
        RbPlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbPltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RbSlv, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RbGld, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(RbPlt)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbSlv)
                    .addComponent(RbGld)
                    .addComponent(RbPlt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LblRoomPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblRoomPic.setIcon(new ImageIcon());
        LblRoomPic.setText("Room Image");
        LblRoomPic.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(153, 153, 153)));
        LblRoomPic.setMaximumSize(new java.awt.Dimension(50, 24));
        LblRoomPic.setMinimumSize(new java.awt.Dimension(40, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addComponent(LblRoomPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblRoomPic, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNext)
                    .addComponent(BtnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        (new Main_Menu()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNextActionPerformed
        (new Room_Selection()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnNextActionPerformed

    private void RbSlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbSlvActionPerformed
        LblRoomPic.setIcon( new ImageIcon("Silver Class Room.jpg"));
                
    }//GEN-LAST:event_RbSlvActionPerformed

    private void RbGldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbGldActionPerformed
        LblRoomPic.setIcon( new ImageIcon("Gold Class Room.jpg"));
    }//GEN-LAST:event_RbGldActionPerformed

    private void RbPltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbPltActionPerformed
        LblRoomPic.setIcon( new ImageIcon("Platinum Class Room.jpg"));
    }//GEN-LAST:event_RbPltActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms_Preview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BgRoomType;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnNext;
    private javax.swing.JLabel LblRoomPic;
    private javax.swing.JRadioButton RbGld;
    private javax.swing.JRadioButton RbPlt;
    private javax.swing.JRadioButton RbSlv;
    private javax.swing.JTextArea TxtArRoomDesc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
