
import javax.swing.table.*;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Room_Modify.java
 *
 * Created on Nov 25, 2014, 11:45:17 AM
 */

/**
 *
 * @author student
 */
public class Room_Modify extends javax.swing.JFrame {

    /** Creates new form Room_Modify */
    public Room_Modify() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgAddRooms = new javax.swing.ButtonGroup();
        BgModifyCharges = new javax.swing.ButtonGroup();
        BgSearch = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        RbAddSlv = new javax.swing.JRadioButton();
        RbAddGld = new javax.swing.JRadioButton();
        RbAddPlt = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        TxtFdNoOfRoom = new javax.swing.JTextField();
        BtnAddRoom = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        RbModSlv = new javax.swing.JRadioButton();
        RbModGld = new javax.swing.JRadioButton();
        RbModPlt = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        TxtFdRoomCharge = new javax.swing.JTextField();
        BtnModifyCharge = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSearch = new javax.swing.JTable();
        RbSearchCat = new javax.swing.JRadioButton();
        RbSearchRoomNo = new javax.swing.JRadioButton();
        TxtFdSearchCat = new javax.swing.JTextField();
        TxtFdSearchRoomNo = new javax.swing.JTextField();
        BtnSearch = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Room Modify");

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ROOMS MODIFICATION");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD ROOMS :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category :", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        BgAddRooms.add(RbAddSlv);
        RbAddSlv.setText("SILVER CLASS");
        RbAddSlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbAddSlvActionPerformed(evt);
            }
        });

        BgAddRooms.add(RbAddGld);
        RbAddGld.setText("GOLD CLASS");
        RbAddGld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbAddGldActionPerformed(evt);
            }
        });

        BgAddRooms.add(RbAddPlt);
        RbAddPlt.setText("PLATINUM CLASS");
        RbAddPlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbAddPltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RbAddSlv)
                    .addComponent(RbAddGld)
                    .addComponent(RbAddPlt))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(RbAddSlv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbAddGld)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RbAddPlt))
        );

        jLabel2.setText("No. of Rooms    :");

        BtnAddRoom.setText("ADD ROOMS");
        BtnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtFdNoOfRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(BtnAddRoom)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFdNoOfRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(BtnAddRoom)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MODIFY CHARGES :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category :", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        BgModifyCharges.add(RbModSlv);
        RbModSlv.setText("SILVER CLASS");
        RbModSlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbModSlvActionPerformed(evt);
            }
        });

        BgModifyCharges.add(RbModGld);
        RbModGld.setText("GOLD CLASS");
        RbModGld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbModGldActionPerformed(evt);
            }
        });

        BgModifyCharges.add(RbModPlt);
        RbModPlt.setText("PLATINUM CLASS");
        RbModPlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbModPltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RbModSlv)
                    .addComponent(RbModGld)
                    .addComponent(RbModPlt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(RbModSlv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbModGld)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RbModPlt))
        );

        jLabel3.setText("Charges (in Rupees) :");

        BtnModifyCharge.setText("MODIFY");
        BtnModifyCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifyChargeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtFdRoomCharge, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(BtnModifyCharge)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFdRoomCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(BtnModifyCharge)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEARCH FOR OCCUPANTS :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        TableSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ROOM NO.", "GUEST ID", "GUEST NAME", "MOBILE NO.", "COMPANIONS", "CHECK-IN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableSearch);

        BgSearch.add(RbSearchCat);
        RbSearchCat.setText("Enter Category :");
        RbSearchCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbSearchCatActionPerformed(evt);
            }
        });

        BgSearch.add(RbSearchRoomNo);
        RbSearchRoomNo.setText("Enter Room No. :");
        RbSearchRoomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbSearchRoomNoActionPerformed(evt);
            }
        });

        BtnSearch.setText("SEARCH");
        BtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RbSearchCat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFdSearchCat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtFdSearchRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RbSearchRoomNo))
                .addGap(44, 44, 44))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RbSearchCat)
                    .addComponent(RbSearchRoomNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFdSearchCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFdSearchRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );

        BtnBack.setText("BACK");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddRoomActionPerformed
        String room_no, room_cat="", cat="";
        int charges, qty, p=1 ;
        
        qty = Integer.parseInt(TxtFdNoOfRoom.getText());
        
        if(RbAddSlv.isSelected())
        {
            room_cat = "SL0";
            cat = "Silver";
        }
        
        else if(RbAddGld.isSelected())
        {
            room_cat = "GD0";
            cat = "Gold";
        }
        
        else if(RbAddPlt.isSelected())
        {
            room_cat = "PT0";
            cat = "Platinum";
        }
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aditya_sud?user="+"root"+"&password="+"MYSQL");
            
            Statement stmt = con.createStatement();
            
            for(; p<=qty ; p++)
            {
                String Q1 ="Select * from Room where Class='" + cat +"'" ;
                ResultSet rs1 = stmt.executeQuery(Q1);
                rs1.next();
                charges = rs1.getInt("Charges");
                rs1.last();
                int i = rs1.getRow();
                room_no = room_cat +(i+1);
            
                String Q2 ="Insert into Room values('" + room_no + "','" + cat + "','N'," + charges + ")";
                stmt.executeUpdate(Q2);
            }
            
            JOptionPane.showMessageDialog(this, "" + (p-1) + " rooms of " + cat + " Class have been added.");
            
            }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
    }//GEN-LAST:event_BtnAddRoomActionPerformed

    private void RbAddSlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbAddSlvActionPerformed
        // TODO add your handling code here:
        TxtFdNoOfRoom.setText("");
        
    }//GEN-LAST:event_RbAddSlvActionPerformed

    private void RbAddGldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbAddGldActionPerformed
        // TODO add your handling code here:
        TxtFdNoOfRoom.setText("");
        
    }//GEN-LAST:event_RbAddGldActionPerformed

    private void RbAddPltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbAddPltActionPerformed
        // TODO add your handling code here:
        TxtFdNoOfRoom.setText("");
        
    }//GEN-LAST:event_RbAddPltActionPerformed

    private void BtnModifyChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifyChargeActionPerformed
        String cat="";
        int charge;
        
        charge = Integer.parseInt(TxtFdRoomCharge.getText());
        
        if(RbModSlv.isSelected())
        {
            cat = "Silver";
        }
        
        else if(RbModGld.isSelected())
        {
            cat = "Gold";
        }
        
        else if(RbModPlt.isSelected())
        {
            cat = "Platinum";
        }
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aditya_sud?user="+"root"+"&password="+"MYSQL");
            
            Statement stmt = con.createStatement();
            
            String Q1 ="Update Room set Charges=" + charge + " where Class='" + cat +"'" ;
            stmt.executeUpdate(Q1);
            
            JOptionPane.showMessageDialog(this, "New charges for rooms of " + cat + " Class are Rs." + charge);
            
            }
        
        catch (Exception e)
            {
            JOptionPane.showMessageDialog(this, e.getMessage());
            }
        
        
    }//GEN-LAST:event_BtnModifyChargeActionPerformed

    private void RbModSlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbModSlvActionPerformed
        // TODO add your handling code here:
        TxtFdRoomCharge.setText("");
    }//GEN-LAST:event_RbModSlvActionPerformed

    private void RbModGldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbModGldActionPerformed
        // TODO add your handling code here:
        TxtFdRoomCharge.setText("");
    }//GEN-LAST:event_RbModGldActionPerformed

    private void RbModPltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbModPltActionPerformed
        // TODO add your handling code here:
        TxtFdRoomCharge.setText("");
    }//GEN-LAST:event_RbModPltActionPerformed

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        String cat, room_no;
        
        if(TxtFdSearchCat.isEditable())
        {    
        cat = TxtFdSearchCat.getText();
        }
        else cat = "*****";
        
        room_no = TxtFdSearchRoomNo.getText();
        
        DefaultTableModel TableSearchModel = (DefaultTableModel) TableSearch.getModel();
        // Clear the existing table
        int rows = TableSearchModel.getRowCount();
        if (rows > 0) {
            for (int i = 0; i < rows; i++) {
                TableSearchModel.removeRow(0);
            }
        }
       
        
        try {
            // Connect to MySQL database
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/aditya_sud?user="+"root"+"&password="+"MYSQL");

            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            
            String Q1 ="Select Room_No, G_Id, Name, Mob_No, Companions, Check_In from Room r natural join Guest_Details g where r.Status=g.G_Id AND (Room_No='" +room_no + "' OR Class Like('%" + cat + "%'))" ;
            ResultSet rs1 = stmt.executeQuery(Q1);

            // Iterate through the result and display on screen
            while (rs1.next()) 
            {
                String Room_No = rs1.getString("Room_No");
                String G_Id = rs1.getString("G_Id");
                String Name = rs1.getString("Name");
                long    Mob_No = rs1.getLong("Mob_No");
                String Companions = rs1.getString("Companions");
                String Check_In = rs1.getString("Check_In");
                TableSearchModel.addRow(new Object[] {Room_No, G_Id, Name, Mob_No, Companions, Check_In});

            }
            
            } 
        catch (Exception e) 
            {
            JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_BtnSearchActionPerformed

    private void RbSearchCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbSearchCatActionPerformed
        // TODO add your handling code here:
        TxtFdSearchCat.setEditable(true);
        TxtFdSearchRoomNo.setText("");
        TxtFdSearchRoomNo.setEditable(false);
    }//GEN-LAST:event_RbSearchCatActionPerformed

    private void RbSearchRoomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbSearchRoomNoActionPerformed
        // TODO add your handling code here:
        TxtFdSearchRoomNo.setEditable(true);
        TxtFdSearchCat.setText("");
        TxtFdSearchCat.setEditable(false);

    }//GEN-LAST:event_RbSearchRoomNoActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        (new Maintenance_Menu()).setVisible(true);
         this.setVisible(false);
}//GEN-LAST:event_BtnBackActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Additional_Charges_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room_Modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BgAddRooms;
    private javax.swing.ButtonGroup BgModifyCharges;
    private javax.swing.ButtonGroup BgSearch;
    private javax.swing.JButton BtnAddRoom;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnModifyCharge;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JRadioButton RbAddGld;
    private javax.swing.JRadioButton RbAddPlt;
    private javax.swing.JRadioButton RbAddSlv;
    private javax.swing.JRadioButton RbModGld;
    private javax.swing.JRadioButton RbModPlt;
    private javax.swing.JRadioButton RbModSlv;
    private javax.swing.JRadioButton RbSearchCat;
    private javax.swing.JRadioButton RbSearchRoomNo;
    private javax.swing.JTable TableSearch;
    private javax.swing.JTextField TxtFdNoOfRoom;
    private javax.swing.JTextField TxtFdRoomCharge;
    private javax.swing.JTextField TxtFdSearchCat;
    private javax.swing.JTextField TxtFdSearchRoomNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
